on:
  workflow_dispatch:

jobs:
  UPLOAD-TO-REPOSITORY:
    runs-on: self-hosted  
 
    steps:
      # 1️⃣ Checkout first
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Power Platform Tools
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # 3️⃣ Remove old solution zip if exists
      - name: Remove old solution zip if exists
        shell: powershell
        run: |
          if (Test-Path -Path 'out/POC.zip') {
              Remove-Item -Path 'out/POC.zip' -Force
          }


# Authenticate to EPS_DEV environment
      - name: Authenticate to Power Platform Environment (EPS_DEV)
        shell: powershell
        run: |
          pac auth create --environment 'https://org160d1bc2.crm.dynamics.com' --username 'sa_svc_eps_intake@arcadis.com' --password '${{ secrets.NOA_PP_SECRET }}'
          
      # Export Solution (unmanaged) - remove zip if exists!
      - name: Export Solution
        shell: powershell
        run: |
          if (!(Test-Path -Path 'out')) { New-Item -ItemType Directory -Path 'out' }
          if (Test-Path -Path 'out/POC.zip') {
              Remove-Item -Path 'out/POC.zip' -Force
          }
          pac solution export --name 'NOAReusableComponentsSolution' --path 'out/POC.zip'

      # Unpack Solution (unmanaged)
      - name: Unpack Solution
        shell: powershell
        run: |
          if (!(Test-Path -Path 'out/solutions/POC')) { New-Item -ItemType Directory -Path 'out/solutions/POC' }
          pac solution unpack --zipfile 'out/POC.zip' --folder 'out/solutions/POC' --packagetype Unmanaged --clobber


      # 7️⃣ Prepare solution changes for check-in into source control
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/POC'
          solution-target-folder: 'src/solutions/POC'
          token: ${{ secrets.GITHUB_TOKEN }}
