jobs:
  import-to-production:
    runs-on: self-hosted
    environment: PROD - POC    # This must match the name of your created environment!
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import Solution to Production
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://org6a8a6dc7.crm.dynamics.com/'
          user-name: 'sa_svc_eps_intake@arcadis.com'
          password-secret: ${{ secrets.NOA_PP_SECRET }}
          solution-file: 'out/POC.zip'

