on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  
 
    steps:


      # Install Power Platform Tools
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Remove old solution zip if exists
      - name: Remove old solution zip if exists
        shell: powershell
        run: |
          if (Test-Path -Path 'out/POC.zip') {
              Remove-Item -Path 'out/POC.zip' -Force
          }

      # Export Solution
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org160d1bc2.crm.dynamics.com'   # EPS_DEV environment
          user-name: 'sa_svc_eps_intake@arcadis.com'
          password-secret: ${{ secrets.NOA_PP_SECRET }}
          solution-name: 'POC'
          solution-output-file: 'POC.zip'
          working-directory: 'out'
          managed: true


      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://org82c8d52d.crm.dynamics.com/'     # Target environment (EPS_DEV or your desired env)
          user-name: 'sa_svc_eps_intake@arcadis.com'
          password-secret: ${{ secrets.NOA_PP_SECRET }}
          solution-file: 'out/POC.zip'
          # Optional: set 'async' to true for large solutions
          # async: false
          

      # Unpack Solution
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/POC.zip'
          solution-folder: 'out/solutions/POC'
          solution-type: 'Managed'
          overwrite-files: true

      # Prepare solution changes for check-in into source control
      - name: Prepare solution changes for check-in
        shell: powershell
        run: |
          if (!(Test-Path -Path 'src/solutions/POC')) { New-Item -ItemType Directory -Path 'src/solutions/POC' }
          Copy-Item -Path 'out/solutions/POC\*' -Destination 'src/solutions/POC' -Recurse -Force

      # check-in into source control
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/POC'
          solution-target-folder: 'src/solutions/POC'
          token: ${{ secrets.GITHUB_TOKEN }}
